---
version: "2.0"

services:
  app:
    image: dimokus88/ironfish:0.0.4
    env:
     - "my_root_password=pass_root_for_ssh" #Введите пароль пользователя root для подключения к контейнеру по ssh.
     #- "account_name=Your_acc_name" # Придумайте и введите имя кошелька(аккаунта).Если запускаете ноду 1й раз и у вас нет wallet.json, заккоментируйте переменную LINK_WALLET
     #- "LINK_WALLET=https://drive.google.com/uc?export=download&" # Прямая ссылка на скачивание вашего wallet.json . Если используете эту переменную закомментируйте account_name
     - "NODE_NAME=" # Имя ноды
     - "Graffiti=" # Граффити из личного кабинета https://testnet.ironfish.network/
     - "EMAIL=" # почтовый адрес, на который зарегистрирован личный кабинет https://testnet.ironfish.network/
     - "POOL=pool.ironfish.network" # майнинговый пул ironfish
     
    
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
   
    
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 6.0
        memory:
          size: 8Gi
        storage:
          size: 10Gi
        
        
  placement:
    akash: 
      attributes:
        host: akash
      signedBy:
        anyOf:
            
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 #max 2 count
