---
version: "2.0"

services:
  app:
    image: dimokus88/ironfish:0.0.4
    env:
     - "my_root_password=pass_root_for_ssh" 
     #- "account_name=Your_acc_name" 
     №- "LINK_WALLET="
     - "NODE_NAME="
     - "Graffiti="
     - "EMAIL=" 
     - "POOL=pool.ironfish.network" 
     
    
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
   
    
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 6.0
        memory:
          size: 8Gi
        storage:
          size: 10Gi
        
        
  placement:
    akash: 
      attributes:
        host: akash
      signedBy:
        anyOf:
            
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 #max 2 count
