---
version: "2.0"

services:
  app:
    image: dimokus88/ironfish:0.2.3
    env:
      - "my_root_password=" 
      - "LINK_WALLET="
      - "NODE_NAME="
      - "Graffiti="
      - "EMAIL=" 
      - "POOL=pool.ironfish.network" 
      - "LINK_SNAPSHOT=http://p7egqbi5ah8u36d94661kutalg.ingress.bigtractorplotting.com/databases.zip" 
     
    
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
    params:
      storage:
        data:
          mount: /root/.ironfish/
    
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 6Gi
        storage:
        - size: 4Gi
        - name: data
          size: 4Gi
          attributes:
            persistent: true
            class: beta2
        
        
  placement:
    akash: 
      attributes:
        host: akash
      signedBy:
        anyOf:
            
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 #max 2 count
